### ISSUE TITLE
Scrolling may be temporarily blocked when keyboard is active on iOS/iPadOS

### ISSUE THREAD

**Issue by wxwern** [wernjie/personal-diary#13]
When a user attempts to scroll entry content, the user may not be able to scroll up from the bottom if their text goes underneath the keyboard. This appears to be caused by the UI not being correctly updated to fit in the empty space above the keyboard.

On iOS 14 and iPadOS 14 or later, a workaround is while the keyboard is active for at least a second (i.e. animations have stopped completely), simply perform a single-tap anywhere on the entry text, and scrolling should subsequently work as expected.

On older iOS and iPadOS versions, a workaround is to rotate your device, and then rotate back. For instance, while the keyboard is up in portrait mode on an iPhone, rotate your phone to landscape, then back to portrait. Scrolling will subsequently work.

**Comment by wxwern** [comment]
This is resolved in version 2.6.1.

**Comment by ooRickoo** [comment]
It would be great if you could use ML to tag log events with tags that a user can setup - user can adjust but tags applied automagically.
