### ISSUE TITLE
Go to present day and time on opening the app?

### ISSUE THREAD

**Issue by Modelflier** [wernjie/personal-diary#24]
I have several future appointments noted in the diary, and every time I open the app it opens with the furthest appointment at the top. Would it be possible to have the option for the app to always open with todays entry at the top?

**Comment by wxwern** [comment]
Thank you for the suggestion @Modelflier! 

I'll add an option to automatically start with today's entry visible in the subsequent update of the app.

**Comment by wxwern** [comment]
This should now be possible on version 3.0.
