### ISSUE TITLE
How am I going to get in it don’t remember passcode

### ISSUE THREAD

**Issue by Vickienaba1** [wernjie/personal-diary#44]

**Comment by wxwern** [comment]
Apologies for the late reply @Vickienaba1.

You should be able to use Recovery Mode to reset your passcode, unless you disabled that. Recovery Mode will attempt to use alternative authentication methods, such as your device password. 

If you have reset your passcode before this, it might have been automatically changed to 0000 or 1234.

If you need further personalized assistance, please contact me via email from within the app.
