### ISSUE TITLE
Separate new entry defaults for mood and weather

### ISSUE THREAD

**Issue by sakofox** [wernjie/personal-diary#46]
### Feature Description

I would like to be able to select the weather and emojis separately. I want to keep the weather but I want to switch off the emojis. Currently I have to have both or nothing.

### Additional Context

If applicable, add any other context, mockups or screenshots about the feature request here, e.g., how existing features do not suit your needs.

**Comment by wxwern** [comment]
Resolved in version 3.0.13

**Comment by sakofox** [comment]
Great, thank you,
Duncan
